trigger:
- main

pool: aron-devops

#container: adoptopenjdk:latest 

steps:
- script: which docker 
  displayName: 'Command line'


# # Starter pipeline
# - task: Gradle@3
#   inputs:
#     gradleWrapperFile: 'gradlew'
#     tasks: 'build'
#     publishJUnitResults: true
#     testResultsFiles: '**/TEST-*.xml'
#     javaHomeOption: 'JDKVersion'
#     sonarQubeRunAnalysis: false
#     spotBugsAnalysis: false
# # Start with a minimal pipeline that you can customize to build and deploy your code.
# # Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

